#used binding.pry to check error
def plus_two(num)
	return num + 2
	//num
end